#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Setting variables

MAX_SLEEP_TIME="${GSP_SLEEP:-60}"
RETRY_DELAY="${GSP_RETRY_DELAY:-10}"
INIT_RETRY_WAIT="${GSP_INIT_RETRY_WAIT:-10}"
GTN_PORT_INDEX="$(( ${GSP_GTN_PORT_INDEX:-1} - 1))"
[ "${MAX_SLEEP_TIME}" -eq "${RETRY_DELAY}" ] && (( RETRY_DELAY = RETRY_DELAY - 1 )) # To avoid errors later
GLUETUN="${GSP_GTN_ADDR:-http://localhost:8000}"
[ -n "${GSP_GTN_API_KEY_FILE}" ] && GSP_GTN_API_KEY="$(cat "${GSP_GTN_API_KEY_FILE}")"
GTN_API_KEY="${GSP_GTN_API_KEY}"
QBITTORRENT="${GSP_QBT_ADDR:-http://localhost:${WEBUI_PORT:-8080}}"
[ -n "${GSP_QBT_PASSWORD_FILE}" ] && GSP_QBT_PASSWORD="$(cat "${GSP_QBT_PASSWORD_FILE}")"
QBT_USERNAME="${GSP_QBT_USERNAME}"
QBT_PASSWORD="${GSP_QBT_PASSWORD}"
QBT_COOKIES="--cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt"

DEBUG="${GSP_DEBUG:-false}"

spaces='                                                            '
QBT_display="${QBITTORRENT}${spaces}"
GTN_display="${GLUETUN}${spaces}"
INDEX_DISPLAY="${GSP_GTN_PORT_INDEX:-1}${spaces}"

GTN_CREDS=("-H" "X-API-Key:${GTN_API_KEY}")

echo "\
+---------------------------------------------------------+
|           Gluetun sync port (GSP) mod loaded            |
+---------------------------------------------------------+
|  Qbittorrent address : ${QBT_display::33}|
|  Gluetun address : ${GTN_display::37}|
|  GTN port index : ${INDEX_DISPLAY::38}|
+---------------------------------------------------------+
"

## Useful functions

log(){
    echo "$(date +"%x %T") [GSP] - ${1}"
}


qbt_login(){
  curl --fail --silent \
      ${QBT_COOKIES} \
      --url "${QBITTORRENT}/api/v2/auth/login" \
      --data "username=${QBT_USERNAME}" \
      --data "password=${QBT_PASSWORD}"
}


# Check the config for common mistakes. Run only once at startup. Can be deactivated.
init_checks(){
  # Enable or not init_checks
  if [ "${GSP_SKIP_INIT_CHECKS,,}" = 'true' ]; then
    return 0
  elif [ "${GSP_SKIP_INIT_CHECKS,,}" = 'warning' ]; then
    MSG_prefix="[WARNING]"
  else
    MSG_prefix="[ERROR]"
  fi


  conf_file='/config/qBittorrent/qBittorrent.conf'

  # Check 1 : 
  #   Check for the auth bypass in qbittorrent's config file,
  #   or check for bad credentials.

  if [ ! -f "${conf_file}" ]; then
    log "${conf_file} not found, can't check the The \"Bypass authentication for clients on localhost\" setting. Running in standalone mode."
  else
    if { [ -z "${QBT_USERNAME}" ] || [ -z "${QBT_PASSWORD}" ] ;} && [ "$(grep 'LocalHostAuth' ${conf_file} | awk -F'=' '{print $2}')" != "false" ]; then
      err='true'
      log "${MSG_prefix} The \"Bypass authentication for clients on localhost\" setting is not set."
    elif [ -n "${QBT_USERNAME}" ] && [ -n "${QBT_PASSWORD}" ] && [ "$(qbt_login)" != "Ok." ]; then
      err='true'
      log "${MSG_prefix} Qbittorrent authentication failed, check the credentials."
    fi
  fi

  # Check 2 :
  #   Check for "Host header validation".
  if [ "$(curl --write-out '%{http_code}' --silent --output /dev/null "${QBITTORRENT}")" -eq 401 ]; then
    err='true'
    log "${MSG_prefix} Qbittorrent returned 401. Is the \"Enable Host header validation\" setting set ? Is $(basename "${QBITTORRENT%:*}") whitelisted ?"
  fi

  # Check 3 :
  #   Check Gluetun's authentication
  if [ -z "${GTN_API_KEY}" ];then
    log "[WARNING] It seems you don't have any 'GSP_GTN_API_KEY' set. You should set one, follow the doc here : https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#gluetun"
  else
    if [ "$(curl --write-out '%{http_code}' --silent --output /dev/null "${GTN_CREDS[@]}" "${GLUETUN}/v1/openvpn/portforwarded")" -eq '401' ]; then
      err='true'
      log "${MSG_prefix} Gluetun returned 401. Is Gluetun's authentication correctly configured ? See https://github.com/t-anc/GSP-Qbittorent-Gluetun-sync-port-mod#gluetun"
    fi
  fi

  # Display Check results.
  # In case of failed checks, enter an empty loop : 
  #   -> exiting the script would make s6-overlay to re-run it.
  if [ "${MSG_prefix}" = '[ERROR]' ]; then
    if [ -n "${err}" ];then
      log "Init checks failed, exiting the mod. You can disable init checks by setting \"GSP_SKIP_INIT_CHECKS=true\"."
      while :; do
        sleep 3600
      done
    else
      log "Init checks passed. Listening for a change."
    fi
  fi
}

# Refresh currently used ports
get_ports(){
  case ${1,,} in
    "qbt")
      QBT='true'
      GTN=''
    ;;
    "gtn")
      QBT=''
      GTN='true'
    ;;
    *)
      QBT='true'
      GTN='true'
    ;;
  esac
  [ "${QBT}" ] && QBT_PORT=$(curl --silent --fail --show-error ${QBT_COOKIES} "${QBITTORRENT}/api/v2/app/preferences" | jq ".listen_port" 2>/dev/null)
  [ "${GTN}" ] && { 
    GTN_PORTS=$(curl  --silent --fail --show-error "${GTN_CREDS[@]}" "${GLUETUN}/v1/openvpn/portforwarded" | jq ".port" 2>/dev/null)
    if  echo "${GTN_PORTS}" | grep -Fq '[' ; then # Handle the case of multiple ports - ex : [10550,20550,30550]
      GTN_PORT=$(echo "${GTN_PORTS}" | jq .[${GTN_PORT_INDEX}] 2>/dev/null) 
      [ "${GTN_PORT}" = "null" ] && log "[ERROR] GSP_GTN_PORT_INDEX (${GSP_GTN_PORT_INDEX:-1}) > Nb of ports ($(( $(echo "${GTN_PORTS}" | grep -c ',') + 1 )))."\
        && GTN_PORT=0
    else
      GTN_PORT="${GTN_PORTS}"
    fi
  }
}

if [ "${DEBUG,,}" = "true" ]; then
  log "Debug mode enabled."
  set -x
fi


log "Waiting for Qbittorrent WebUI ..."
curl --retry "${INIT_RETRY_WAIT}" --retry-all-errors --retry-delay 6 -s -o /dev/null "${QBITTORRENT}" || \
log "Couldn't connect to webUI. Check the address, or maybe your instance is taking to long to start. You can adjust the GSP_INIT_RETRY_WAIT variable to wait longer."


init_checks

# Infinite loop
while :; do
    SLEEP_TIME="${MAX_SLEEP_TIME}"
    if [ -n "${QBT_USERNAME}" ] && [ -n "${QBT_PASSWORD}" ]; then # If login is needed
      qbt_login
    fi

    get_ports

    if [ -z "${GTN_PORT}" ] || [ "${GTN_PORT}" -eq 0 ]; then
        log "Error retrieving port from Gluetun API."
        SLEEP_TIME=${RETRY_DELAY}
    fi
    if [ -z "${QBT_PORT}" ]; then
        log "Error retrieving port from Qbittorrent API."
        SLEEP_TIME=${RETRY_DELAY}
    fi
    if [ "${SLEEP_TIME}" -ne "${RETRY_DELAY}" ]; then # If everything OK
      if [ "${QBT_PORT}" = "${GTN_PORT}" ]; then
          [ "${GSP_MINIMAL_LOGS,,}" = 'false' ] && log "Ports did not change."
      else
          log "Ports changed :"
          log " - Old : ${QBT_PORT}"
          log " - New : ${GTN_PORT}"
          log "Updating qbittorrent port via API ..."
          curl \
              --silent \
              --request POST \
              ${QBT_COOKIES} \
              --url "${QBITTORRENT}/api/v2/app/setPreferences" \
              --data "json={\"listen_port\": $GTN_PORT}"
          
          # get the updated value from qbittorrent
          get_ports "qbt"
          if [ "${QBT_PORT}" = "${GTN_PORT}" ]; then
              log "Qbittorrent port successfully updated."
          else
              log "ERROR updating qbittorrent port !"
              SLEEP_TIME=${RETRY_DELAY}
          fi
      fi
    fi

    sleep "${SLEEP_TIME}"
done
